AllCops:
  Includes:
    - Gemfile
    - Rakefile
  Excludes:
    - vendor/*
    - examples/refactorings/rails/where_first/sample_controller.rb

StringLiterals:
  EnforcedStyle: double_quotes

LineLength:
  Max: 99

Documentation:
  Enabled: false
